<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            //BENI
            [ 'nombre' => 'Trinidad', 'dep_id' => '1' ],
            [ 'nombre' => 'Riberalta', 'dep_id' => '1' ],
            [ 'nombre' => 'Guayaramerin', 'dep_id' => '1' ],
            [ 'nombre' => 'San Borja', 'dep_id' => '1' ],
            [ 'nombre' => 'Rurrenabaque', 'dep_id' => '1' ],
            [ 'nombre' => 'San Ignacio de Moxos', 'dep_id' => '1' ],
            [ 'nombre' => 'Santa Ana del Yacuma', 'dep_id' => '1' ],
            [ 'nombre' => 'San Andrés', 'dep_id' => '1' ],
            [ 'nombre' => 'Magdalena', 'dep_id' => '1' ],
            [ 'nombre' => 'Reyes', 'dep_id' => '1' ],
            [ 'nombre' => 'Santa Rosa de Yacuma', 'dep_id' => '1' ],
            [ 'nombre' => 'San Joaquín', 'dep_id' => '1' ],
            [ 'nombre' => 'Baures', 'dep_id' => '1' ],
            [ 'nombre' => 'San Ramón', 'dep_id' => '1' ],
            [ 'nombre' => 'Exaltación', 'dep_id' => '1' ],
            [ 'nombre' => 'Huacaraje', 'dep_id' => '1' ],
            [ 'nombre' => 'San Javier', 'dep_id' => '1' ],
            [ 'nombre' => 'Loreto', 'dep_id' => '1' ],
            [ 'nombre' => 'Puerto Siles', 'dep_id' => '1' ],
            //CHUQUISACA
            [ 'nombre' => 'Sucre', 'dep_id' => '2' ],
            [ 'nombre' => 'San Lucas', 'dep_id' => '2' ],
            [ 'nombre' => 'Monteagudo', 'dep_id' => '2' ],
            [ 'nombre' => 'Culpina', 'dep_id' => '2' ],
            [ 'nombre' => 'Poroma', 'dep_id' => '2' ],
            [ 'nombre' => 'Tarabuco', 'dep_id' => '2' ],
            [ 'nombre' => 'Villa Charcas', 'dep_id' => '2' ],
            [ 'nombre' => 'Camargo', 'dep_id' => '2' ],
            [ 'nombre' => 'Tarvita', 'dep_id' => '2' ],
            [ 'nombre' => 'Incahuasi', 'dep_id' => '2' ],
            [ 'nombre' => 'Presto', 'dep_id' => '2' ],
            [ 'nombre' => 'Zudáñez', 'dep_id' => '2' ],
            [ 'nombre' => 'Villa Serrano', 'dep_id' => '2' ],
            [ 'nombre' => 'Azurduy', 'dep_id' => '2' ],
            [ 'nombre' => 'Padilla', 'dep_id' => '2' ],
            [ 'nombre' => 'Yamparáez', 'dep_id' => '2' ],
            [ 'nombre' => 'Muyupampa', 'dep_id' => '2' ],
            [ 'nombre' => 'Yotala', 'dep_id' => '2' ],
            [ 'nombre' => 'Tomina', 'dep_id' => '2' ],
            [ 'nombre' => 'Huacareta', 'dep_id' => '2' ],
            [ 'nombre' => 'Mojocoya', 'dep_id' => '2' ],
            [ 'nombre' => 'Icla', 'dep_id' => '2' ],
            [ 'nombre' => 'Macharetí', 'dep_id' => '2' ],
            [ 'nombre' => 'Sopachuy', 'dep_id' => '2' ],
            [ 'nombre' => 'Villa Alcalá', 'dep_id' => '2' ],
            [ 'nombre' => 'El Villar', 'dep_id' => '2' ],
            [ 'nombre' => 'Las Carreras', 'dep_id' => '2' ],
            [ 'nombre' => 'Villa Abecia', 'dep_id' => '2' ],
            [ 'nombre' => 'Huacaya', 'dep_id' => '2' ],
            //COCHABAMBA
            [ 'nombre' => 'Cochabamba', 'dep_id' => '3'],
            [ 'nombre' => 'Sacaba', 'dep_id' => '3'],
            [ 'nombre' => 'Quillacollo', 'dep_id' => '3'],
            [ 'nombre' => 'Villa Tunari', 'dep_id' => '3'],
            [ 'nombre' => 'Tiquipaya', 'dep_id' => '3'],
            [ 'nombre' => 'Colcapirhua', 'dep_id' => '3'],
            [ 'nombre' => 'Vinto', 'dep_id' => '3'],
            [ 'nombre' => 'Puerto Villaroel', 'dep_id' => '3'],
            [ 'nombre' => 'Sipe Sipe', 'dep_id' => '3'],
            [ 'nombre' => 'Entre Ríos', 'dep_id' => '3'],
            [ 'nombre' => 'Punata', 'dep_id' => '3'],
            [ 'nombre' => 'Mizque', 'dep_id' => '3'],
            [ 'nombre' => 'Tapacari', 'dep_id' => '3'],
            [ 'nombre' => 'Independencia', 'dep_id' => '3'],
            [ 'nombre' => 'Aiquile', 'dep_id' => '3'],
            [ 'nombre' => 'Cliza', 'dep_id' => '3'],
            [ 'nombre' => 'Chimoré', 'dep_id' => '3'],
            [ 'nombre' => 'Tiraque', 'dep_id' => '3'],
            [ 'nombre' => 'Shinahota', 'dep_id' => '3'],
            [ 'nombre' => 'Colomi', 'dep_id' => '3'],
            [ 'nombre' => 'Capinota', 'dep_id' => '3'],
            [ 'nombre' => 'Cocapata', 'dep_id' => '3'],
            [ 'nombre' => 'Arbieto', 'dep_id' => '3'],
            [ 'nombre' => 'Totora', 'dep_id' => '3'],
            [ 'nombre' => 'San Benito', 'dep_id' => '3'],
            [ 'nombre' => 'Morochata', 'dep_id' => '3'],
            [ 'nombre' => 'Pocona', 'dep_id' => '3'],
            [ 'nombre' => 'Arque', 'dep_id' => '3'],
            [ 'nombre' => 'Tacopaya', 'dep_id' => '3'],
            [ 'nombre' => 'Pojo', 'dep_id' => '3'],
            [ 'nombre' => 'Arani', 'dep_id' => '3'],
            [ 'nombre' => 'Vacas', 'dep_id' => '3'],
            [ 'nombre' => 'Tarata', 'dep_id' => '3'],
            [ 'nombre' => 'Villa Rivero', 'dep_id' => '3'],
            [ 'nombre' => 'Bolívar', 'dep_id' => '3'],
            [ 'nombre' => 'Anzaldo', 'dep_id' => '3'],
            [ 'nombre' => 'Toco', 'dep_id' => '3'],
            [ 'nombre' => 'Pasorapa', 'dep_id' => '3'],
            [ 'nombre' => 'Santiváñez', 'dep_id' => '3'],
            [ 'nombre' => 'Omereque', 'dep_id' => '3'],
            [ 'nombre' => 'Tolata', 'dep_id' => '3'],
            [ 'nombre' => 'Vila Vila', 'dep_id' => '3'],
            [ 'nombre' => 'Sacabamba', 'dep_id' => '3'],
            [ 'nombre' => 'Sicaya', 'dep_id' => '3'],
            [ 'nombre' => 'Alalay', 'dep_id' => '3'],
            [ 'nombre' => 'Cuchumuela', 'dep_id' => '3'],
            [ 'nombre' => 'Tacachi', 'dep_id' => '3'],
            //LA PAZ
            [ 'nombre' => 'El Alto' , 'dep_id' => '4'],
            [ 'nombre' => 'La Paz' , 'dep_id' => '4'],
            [ 'nombre' => 'Viacha' , 'dep_id' => '4'],
            [ 'nombre' => 'Caranavi' , 'dep_id' => '4'],
            [ 'nombre' => 'Achacachi' , 'dep_id' => '4'],
            [ 'nombre' => 'La Asunta' , 'dep_id' => '4'],
            [ 'nombre' => 'Sica Sica' , 'dep_id' => '4'],
            [ 'nombre' => 'Pucarani' , 'dep_id' => '4'],
            [ 'nombre' => 'Palos Blancos' , 'dep_id' => '4'],
            [ 'nombre' => 'Laja' , 'dep_id' => '4'],
            [ 'nombre' => 'Sorata' , 'dep_id' => '4'],
            [ 'nombre' => 'Patacamaya' , 'dep_id' => '4'],
            [ 'nombre' => 'Achocalla' , 'dep_id' => '4'],
            [ 'nombre' => 'Apolo' , 'dep_id' => '4'],
            [ 'nombre' => 'Colquiri' , 'dep_id' => '4'],
            [ 'nombre' => 'Coroico' , 'dep_id' => '4'],
            [ 'nombre' => 'Chulumani' , 'dep_id' => '4'],
            [ 'nombre' => 'Batallas' , 'dep_id' => '4'],
            [ 'nombre' => 'Irupana' , 'dep_id' => '4'],
            [ 'nombre' => 'Coripata' , 'dep_id' => '4'],
            [ 'nombre' => 'Palca' , 'dep_id' => '4'],
            [ 'nombre' => 'Mecapaca' , 'dep_id' => '4'],
            [ 'nombre' => 'Mocomoco' , 'dep_id' => '4'],
            [ 'nombre' => 'Jesús de Machaca' , 'dep_id' => '4'],
            [ 'nombre' => 'Copacabana' , 'dep_id' => '4'],
            [ 'nombre' => 'Guanay' , 'dep_id' => '4'],
            [ 'nombre' => 'Inquisivi' , 'dep_id' => '4'],
            [ 'nombre' => 'Caquiaviri' , 'dep_id' => '4'],
            [ 'nombre' => 'Carabuco' , 'dep_id' => '4'],
            [ 'nombre' => 'Mapiri' , 'dep_id' => '4'],
            [ 'nombre' => 'Ancoraimes' , 'dep_id' => '4'],
            [ 'nombre' => 'Charazani' , 'dep_id' => '4'],
            [ 'nombre' => 'Sapahaqui' , 'dep_id' => '4'],
            [ 'nombre' => 'Calamarca' , 'dep_id' => '4'],
            [ 'nombre' => 'Tiahuanacu' , 'dep_id' => '4'],
            [ 'nombre' => 'Chuma' , 'dep_id' => '4'],
            [ 'nombre' => 'Cairoma' , 'dep_id' => '4'],
            [ 'nombre' => 'Puerto Acosta' , 'dep_id' => '4'],
            [ 'nombre' => 'Alto Beni' , 'dep_id' => '4'],
            [ 'nombre' => 'Luribay' , 'dep_id' => '4'],
            [ 'nombre' => 'Corocoro' , 'dep_id' => '4'],
            [ 'nombre' => 'Cajuata' , 'dep_id' => '4'],
            [ 'nombre' => 'Tipuani' , 'dep_id' => '4'],
            [ 'nombre' => 'Calacoto' , 'dep_id' => '4'],
            [ 'nombre' => 'Colquencha' , 'dep_id' => '4'],
            [ 'nombre' => 'Ixiamas' , 'dep_id' => '4'],
            [ 'nombre' => 'Teoponte' , 'dep_id' => '4'],
            [ 'nombre' => 'Umala' , 'dep_id' => '4'],
            [ 'nombre' => 'San Pedro de Curahuara' , 'dep_id' => '4'],
            [ 'nombre' => 'San Buenaventura' , 'dep_id' => '4'],
            [ 'nombre' => 'Santiago de Huata' , 'dep_id' => '4'],
            [ 'nombre' => 'Ayata' , 'dep_id' => '4'],
            [ 'nombre' => 'Quime' , 'dep_id' => '4'],
            [ 'nombre' => 'Tacacoma' , 'dep_id' => '4'],
            [ 'nombre' => 'Puerto Pérez' , 'dep_id' => '4'],
            [ 'nombre' => 'Huarina' , 'dep_id' => '4'],
            [ 'nombre' => 'Ichoca' , 'dep_id' => '4'],
            [ 'nombre' => 'Ayo Ayo' , 'dep_id' => '4'],
            [ 'nombre' => 'Yaco' , 'dep_id' => '4'],
            [ 'nombre' => 'Callapa' , 'dep_id' => '4'],
            [ 'nombre' => 'Guaqui' , 'dep_id' => '4'],
            [ 'nombre' => 'Escoma' , 'dep_id' => '4'],
            [ 'nombre' => 'Papel Pampa' , 'dep_id' => '4'],
            [ 'nombre' => 'Desaguadero' , 'dep_id' => '4'],
            [ 'nombre' => 'Pelechuco' , 'dep_id' => '4'],
            [ 'nombre' => 'Taraco' , 'dep_id' => '4'],
            [ 'nombre' => 'Yanacachi' , 'dep_id' => '4'],
            [ 'nombre' => 'Tito Yupanqui' , 'dep_id' => '4'],
            [ 'nombre' => 'San Andrés de Machaca' , 'dep_id' => '4'],
            [ 'nombre' => 'San Pedro de Tiquina' , 'dep_id' => '4'],
            [ 'nombre' => 'Aucapata' , 'dep_id' => '4'],
            [ 'nombre' => 'Villa Libertad Licoma' , 'dep_id' => '4'],
            [ 'nombre' => 'Humanata' , 'dep_id' => '4'],
            [ 'nombre' => 'Malla' , 'dep_id' => '4'],
            [ 'nombre' => 'Waldo Ballivián' , 'dep_id' => '4'],
            [ 'nombre' => 'Collana' , 'dep_id' => '4'],
            [ 'nombre' => 'Chua Cocani' , 'dep_id' => '4'],
            [ 'nombre' => 'Santiago de Machaca' , 'dep_id' => '4'],
            [ 'nombre' => 'Huatajata' , 'dep_id' => '4'],
            [ 'nombre' => 'Comanche' , 'dep_id' => '4'],
            [ 'nombre' => 'Combaya' , 'dep_id' => '4'],
            [ 'nombre' => 'Curva' , 'dep_id' => '4'],
            [ 'nombre' => 'Charaña' , 'dep_id' => '4'],
            [ 'nombre' => 'Catacora' , 'dep_id' => '4'],
            [ 'nombre' => 'Quiabaya' , 'dep_id' => '4'],
            [ 'nombre' => 'Chacarilla' , 'dep_id' => '4'],
            [ 'nombre' => 'Nazacara de Pacajes' , 'dep_id' => '4'],
            //ORURO
            [ 'nombre' => 'Oruro', 'dep_id' => '5' ],
            [ 'nombre' => 'Challapata', 'dep_id' => '5' ],
            [ 'nombre' => 'Huanuni', 'dep_id' => '5' ],
            [ 'nombre' => 'Caracollo', 'dep_id' => '5' ],
            [ 'nombre' => 'Huari', 'dep_id' => '5' ],
            [ 'nombre' => 'Soracachi', 'dep_id' => '5' ],
            [ 'nombre' => 'Salinas de Garci Mendoza', 'dep_id' => '5' ],
            [ 'nombre' => 'Toledo', 'dep_id' => '5' ],
            [ 'nombre' => 'Corque', 'dep_id' => '5' ],
            [ 'nombre' => 'El Choro', 'dep_id' => '5' ],
            [ 'nombre' => 'Sabaya', 'dep_id' => '5' ],
            [ 'nombre' => 'Poopó', 'dep_id' => '5' ],
            [ 'nombre' => 'Pazña', 'dep_id' => '5' ],
            [ 'nombre' => 'Totora', 'dep_id' => '5' ],
            [ 'nombre' => 'Huayllamarca', 'dep_id' => '5' ],
            [ 'nombre' => 'Eucaliptus', 'dep_id' => '5' ],
            [ 'nombre' => 'Santiago de Andamarca', 'dep_id' => '5' ],
            [ 'nombre' => 'Turco', 'dep_id' => '5' ],
            [ 'nombre' => 'Machacamarca', 'dep_id' => '5' ],
            [ 'nombre' => 'Escara', 'dep_id' => '5' ],
            [ 'nombre' => 'Curahuara de Carangas', 'dep_id' => '5' ],
            [ 'nombre' => 'Santuario de Quillacas', 'dep_id' => '5' ],
            [ 'nombre' => 'Antequera', 'dep_id' => '5' ],
            [ 'nombre' => 'Pampa Aullagas', 'dep_id' => '5' ],
            [ 'nombre' => 'Esmeralda', 'dep_id' => '5' ],
            [ 'nombre' => 'Belén de Andamarca', 'dep_id' => '5' ],
            [ 'nombre' => 'Chipaya', 'dep_id' => '5' ],
            [ 'nombre' => 'Cruz de Machacamarca', 'dep_id' => '5' ],
            [ 'nombre' => 'Choque Cota', 'dep_id' => '5' ],
            [ 'nombre' => 'Huachacalla', 'dep_id' => '5' ],
            [ 'nombre' => 'Coipasa', 'dep_id' => '5' ],
            [ 'nombre' => 'Carangas', 'dep_id' => '5' ],
            [ 'nombre' => 'Todos Santos', 'dep_id' => '5' ],
            [ 'nombre' => 'Yunguyo del Litoral', 'dep_id' => '5' ],
            [ 'nombre' => 'La Rivera', 'dep_id' => '5' ],
            //PANDO
            [ 'nombre' => 'Santa Rosa del Abuná', 'dep_id' => '6' ],
            [ 'nombre' => 'Ingavi', 'dep_id' => '6' ],
            [ 'nombre' => 'Nueva Esperanza', 'dep_id' => '6' ],
            [ 'nombre' => 'Villa Nueva', 'dep_id' => '6' ],
            [ 'nombre' => 'Santos Mercado', 'dep_id' => '6' ],
            [ 'nombre' => 'Puerto Gonzalo Moreno', 'dep_id' => '6' ],
            [ 'nombre' => 'San Lorenzo', 'dep_id' => '6' ],
            [ 'nombre' => 'Sena', 'dep_id' => '6' ],
            [ 'nombre' => 'Puerto Rico', 'dep_id' => '6' ],
            [ 'nombre' => 'San Pedro', 'dep_id' => '6' ],
            [ 'nombre' => 'Filadelfia', 'dep_id' => '6' ],
            [ 'nombre' => 'Cobija', 'dep_id' => '6' ],
            [ 'nombre' => 'Porvenir', 'dep_id' => '6' ],
            [ 'nombre' => 'Bolpebra', 'dep_id' => '6' ],
            [ 'nombre' => 'Bella Flor', 'dep_id' => '6' ],
            //POTOSI
            [ 'nombre' => 'Sacaca', 'dep_id' => '7'],
            [ 'nombre' => 'Caripuyo', 'dep_id' => '7'],
            [ 'nombre' => 'Uyuni', 'dep_id' => '7'],
            [ 'nombre' => 'Tomave', 'dep_id' => '7'],
            [ 'nombre' => 'Porco', 'dep_id' => '7'],
            [ 'nombre' => 'Arampampa', 'dep_id' => '7'],
            [ 'nombre' => 'Acasio', 'dep_id' => '7'],
            [ 'nombre' => 'San Pedro de Buena Vista', 'dep_id' => '7'],
            [ 'nombre' => 'Toro Toro', 'dep_id' => '7'],
            [ 'nombre' => 'Colquechaca', 'dep_id' => '7'],
            [ 'nombre' => 'Ravelo', 'dep_id' => '7'],
            [ 'nombre' => 'Pocoata', 'dep_id' => '7'],
            [ 'nombre' => 'Ocurí', 'dep_id' => '7'],
            [ 'nombre' => 'San Pedro de Macha', 'dep_id' => '7'],
            [ 'nombre' => 'Betanzos', 'dep_id' => '7'],
            [ 'nombre' => 'Chaquí', 'dep_id' => '7'],
            [ 'nombre' => 'Tacobamba', 'dep_id' => '7'],
            [ 'nombre' => 'Llica', 'dep_id' => '7'],
            [ 'nombre' => 'Tahua', 'dep_id' => '7'],
            [ 'nombre' => 'San Agustín', 'dep_id' => '7'],
            [ 'nombre' => 'Puna', 'dep_id' => '7'],
            [ 'nombre' => 'Caiza D', 'dep_id' => '7'],
            [ 'nombre' => 'Ckochas', 'dep_id' => '7'],
            [ 'nombre' => 'Villazón', 'dep_id' => '7'],
            [ 'nombre' => 'Cotagaita', 'dep_id' => '7'],
            [ 'nombre' => 'Vitichi', 'dep_id' => '7'],
            [ 'nombre' => 'Colcha K', 'dep_id' => '7'],
            [ 'nombre' => 'San Pedro de Quemes', 'dep_id' => '7'],
            [ 'nombre' => 'Uncía', 'dep_id' => '7'],
            [ 'nombre' => 'Chayanta', 'dep_id' => '7'],
            [ 'nombre' => 'Llallagua', 'dep_id' => '7'],
            [ 'nombre' => 'Chuquiuta Ayllu Jucumani', 'dep_id' => '7'],
            [ 'nombre' => 'Tupiza', 'dep_id' => '7'],
            [ 'nombre' => 'Atocha', 'dep_id' => '7'],
            [ 'nombre' => 'San Pablo de Lípez', 'dep_id' => '7'],
            [ 'nombre' => 'San Antonio de Esmoruco', 'dep_id' => '7'],
            [ 'nombre' => 'Mojinete', 'dep_id' => '7'],
            [ 'nombre' => 'Potosí', 'dep_id' => '7'],
            [ 'nombre' => 'Tinguipaya', 'dep_id' => '7'],
            [ 'nombre' => 'Yocalla', 'dep_id' => '7'],
            [ 'nombre' => 'Urmiri', 'dep_id' => '7'],
            //SANTA CRUZ
            [ 'nombre' => 'Santa Cruz de la Sierra', 'dep_id' => '8'],
            [ 'nombre' => 'Cotoca', 'dep_id' => '8'],
            [ 'nombre' => 'Porongo o Ayacucho', 'dep_id' => '8'],
            [ 'nombre' => 'La Guardia', 'dep_id' => '8'],
            [ 'nombre' => 'El Torno', 'dep_id' => '8'],
            [ 'nombre' => 'San Matías', 'dep_id' => '8'],
            [ 'nombre' => 'Comarapa', 'dep_id' => '8'],
            [ 'nombre' => 'Saipina', 'dep_id' => '8'],
            [ 'nombre' => 'San José de Chiquitos', 'dep_id' => '8'],
            [ 'nombre' => 'Pailón', 'dep_id' => '8'],
            [ 'nombre' => 'Roboré', 'dep_id' => '8'],
            [ 'nombre' => 'Lagunillas', 'dep_id' => '8'],
            [ 'nombre' => 'Charagua', 'dep_id' => '8'],
            [ 'nombre' => 'Cabezas', 'dep_id' => '8'],
            [ 'nombre' => 'Cuevo', 'dep_id' => '8'],
            [ 'nombre' => 'Gutiérrez', 'dep_id' => '8'],
            [ 'nombre' => 'Camiri', 'dep_id' => '8'],
            [ 'nombre' => 'Boyuibe', 'dep_id' => '8'],
            [ 'nombre' => 'Samaipata', 'dep_id' => '8'],
            [ 'nombre' => 'Pampagrande', 'dep_id' => '8'],
            [ 'nombre' => 'Mairana', 'dep_id' => '8'],
            [ 'nombre' => 'Quirusillas', 'dep_id' => '8'],
            [ 'nombre' => 'Puerto Suárez', 'dep_id' => '8'],
            [ 'nombre' => 'Puerto Quijarro', 'dep_id' => '8'],
            [ 'nombre' => 'El Carmen Rivero Tórrez', 'dep_id' => '8'],
            [ 'nombre' => 'Ascensión de Guarayos', 'dep_id' => '8'],
            [ 'nombre' => 'Urubichá', 'dep_id' => '8'],
            [ 'nombre' => 'El Puente', 'dep_id' => '8'],
            [ 'nombre' => 'Buena Vista', 'dep_id' => '8'],
            [ 'nombre' => 'San Carlos', 'dep_id' => '8'],
            [ 'nombre' => 'Yapacaní', 'dep_id' => '8'],
            [ 'nombre' => 'San Juan de Yapacaní', 'dep_id' => '8'],
            [ 'nombre' => 'Concepción', 'dep_id' => '8'],
            [ 'nombre' => 'San Javier', 'dep_id' => '8'],
            [ 'nombre' => 'San Ramón', 'dep_id' => '8'],
            [ 'nombre' => 'San Julián', 'dep_id' => '8'],
            [ 'nombre' => 'San Antonio de Lomerío', 'dep_id' => '8'],
            [ 'nombre' => 'Cuatro Cañadas', 'dep_id' => '8'],
            [ 'nombre' => 'Montero', 'dep_id' => '8'],
            [ 'nombre' => 'General Saavedra', 'dep_id' => '8'],
            [ 'nombre' => 'Mineros', 'dep_id' => '8'],
            [ 'nombre' => 'Fernández Alonso', 'dep_id' => '8'],
            [ 'nombre' => 'San Pedro', 'dep_id' => '8'],
            [ 'nombre' => 'Portachuelo', 'dep_id' => '8'],
            [ 'nombre' => 'Santa Rosa del Sara', 'dep_id' => '8'],
            [ 'nombre' => 'Colpa Bélgica', 'dep_id' => '8'],
            [ 'nombre' => 'Vallegrande', 'dep_id' => '8'],
            [ 'nombre' => 'El Trigal', 'dep_id' => '8'],
            [ 'nombre' => 'Moro Moro', 'dep_id' => '8'],
            [ 'nombre' => 'Postrervalle', 'dep_id' => '8'],
            [ 'nombre' => 'Pucara', 'dep_id' => '8'],
            [ 'nombre' => 'San Ignacio de Velasco', 'dep_id' => '8'],
            [ 'nombre' => 'San Miguel de Velasco', 'dep_id' => '8'],
            [ 'nombre' => 'San Rafael de Velasco', 'dep_id' => '8'],
            [ 'nombre' => 'Warnes', 'dep_id' => '8'],
            [ 'nombre' => 'Okinawa I', 'dep_id' => '8'],
            //TARIJA
            [ 'nombre' => 'Entre Ríos', 'dep_id' => '9' ],
            [ 'nombre' => 'Tarija', 'dep_id' => '9' ],
            [ 'nombre' => 'Uriondo', 'dep_id' => '9' ],
            [ 'nombre' => 'Yunchará', 'dep_id' => '9' ],
            [ 'nombre' => 'San Lorenzo', 'dep_id' => '9' ],
            [ 'nombre' => 'El Puente', 'dep_id' => '9' ],
            [ 'nombre' => 'Yacuiba', 'dep_id' => '9' ],
            [ 'nombre' => 'Caraparí', 'dep_id' => '9' ],
            [ 'nombre' => 'Villamontes', 'dep_id' => '9' ],
            [ 'nombre' => 'Padcaya', 'dep_id' => '9' ],
            [ 'nombre' => 'Bermejo', 'dep_id' => '9' ],
        ];  

        DB::table('municipios')->insert($data);
    }
}
